### ISSUE TITLE
キーフレームプラグインとの競合について

### ISSUE THREAD

**Issue by infoengine1337** [hebiiro/AviUtl-Plugin-SplitWindow#1]
こんにちは。いつも蛇色氏のプラグインをありがたく使わせてもらっています。
先日SplitWindowを使用していたところ、このプラグインを使用中にrikky氏の開発したプラグインである
"キーフレームプラグイン"(https://www.nicovideo.jp/watch/sm34389463) が動作しなくなる不具合を発見しました。
UniteWindowでは当バグが起きないことを確認済みです。
この不具合について可能でありましたら対処をいただけますと非常にうれしいです。
お忙しいところ恐れ入ります。

**Comment by hebiiro** [comment]
どういう環境でどういうタイミングでどういう症状が出るのか書いてください。

**Comment by infoengine1337** [comment]
わかりました。
システムはIntel(R) Core(TM) i5-9500T CPU @ 2.20GHz   2.21 GHz RAM 8.00GBです。
Splitwindowを導入したAviutlにおいて、キーフレームプラグインのKeyFrame Timelineを選択してもタイムラインの初期化がなされず、結果キーフレームプラグインを利用できないといった状態です。
初期状態のAviutl v1.10 & 拡張編集 v0.92へrikky module&memory バージョンv1 とキーフレームプラグイン 20190104 SplitWindow v3.0.0を導入し、同じ現象が起こることを確認いたしました。
同環境のSplitwindowを導入した環境・していない環境を二つzipファイルで添付します。また確認のために用いたプロジェクト(図形のみがアイテムとして配置されています)も梱包しております。併せてご確認いただけると幸いです。
同問題はUniteWindowでは発生せず、Splitwindow特有の問題であるのではないかと推測します。
よろしくお願いします。
[aviutl110_exedit920.zip](https://github.com/hebiiro/AviUtl-Plugin-SplitWindow/files/9117779/aviutl110_exedit920.zip)

**Comment by hebiiro** [comment]
こちらで再現環境をセットアップする手間が省けたので助かりました。今のところデバッグバージョンで解決できました。

**Comment by hebiiro** [comment]
3.0.1 で改善できたと思います。

**Comment by infoengine1337** [comment]
動作いたしました！！ありがとうございます。
素晴らしいプラグインの開発に心から感謝いたします。
