### ISSUE TITLE
起動後動画を読み込ませた後からショートカットキーがすべて利かなくなる

### ISSUE THREAD

**Issue by toreron4990** [hebiiro/AviUtl-Plugin-SplitWindow#11]
過去に作成したexoファイルを最初に読み込ませた後に動画などを追加で入れた際は通常通りの動作をするのですが
SplitWindow導入後に新たにメディアファイルなどを作成するとその後、すべてのショートカットキーが利かなくなるのですが
私だけでしょうか？

もしやり方があるとかであれば教えていただけると幸いです。

**Comment by toreron4990** [comment]
諸々試しましたが私の環境では
aviutl110
拡張編集92
SplitWindow.4.6.0
の最小構成で試してみても上記症状に陥りました。

**Comment by toreron4990** [comment]
追加情報　なぜか私のエクスポートしたレイアウトだと動かない説があります。
そのレイアウトファイル添付しておきます。
https://xgf.nu/xMzmj

**Comment by hebiiro** [comment]
その最小構成でそのレイアウトファイルを読み込み、拡張編集で新規プロジェクトを作成し、図形アイテムを配置後、Sキーで分割したり左右矢印キーで現在フレームを移動したりしてみましたが、特に問題は発生しませんでした。

**Comment by toreron4990** [comment]
ご確認いただきありがとうございます。
では私の環境依存の可能性が高そうですね。

原因候補の1つが潰せただけでも助かりました。
ありがとうございます。
