### ISSUE TITLE
要望：設定ダイアログを開いたときのモーダルウィンドウの無効化

### ISSUE THREAD

**Issue by laTH380** [hebiiro/AviUtl-Plugin-SplitWindow#14]
設定ダイアログ→フィルタ効果→パラメータ設定を開いた沖のモーダルウィンドウを無効化していただけるとありがたいです。
PSDtoolkitを用いて瞬きや口パクの設定する際にパラメータ設定を開いた状態でPSDtoolkitを操作する必要がありそれができなくなってしまうためです。

**Comment by hebiiro** [comment]
https://github.com/hebiiro/anti.aviutl.ultimate.plugin
アルティメットプラグインのNestを使用してください。

**Comment by laTH380** [comment]
対応プラグインの開発ありがとうございました！無事Nestのおかげで使うことができました
